Migrate to VCDK
Refactoring of this VMOD so that it corresponds
to the schema described in https://git.sr.ht/~dridi/vcdk

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,41 +1,25 @@
 #!/bin/sh
 
-warn() {
-	echo "WARNING: $@" 1>&2
-}
+set -e
+set -u
 
-case `uname -s` in
-Darwin)
-	LIBTOOLIZE=glibtoolize
-	;;
-FreeBSD)
-	LIBTOOLIZE=libtoolize
-	;;
-Linux)
-	LIBTOOLIZE=libtoolize
-	;;
-SunOS)
-	LIBTOOLIZE=libtoolize
-	;;
-*)
-	warn "unrecognized platform:" `uname -s`
-	LIBTOOLIZE=libtoolize
-esac
+WORK_DIR=$(pwd)
+ROOT_DIR=$(dirname "$0")
 
-# check for varnishapi.m4 in custom paths
-dataroot=$(pkg-config --variable=datarootdir varnishapi 2>/dev/null)
-if [ -z "$dataroot" ] ; then
-	cat >&2 <<'EOF'
-Package varnishapi was not found in the pkg-config search path.
-Perhaps you should add the directory containing `varnishapi.pc'
-to the PKG_CONFIG_PATH environment variable
-EOF
-	exit 1
+cd "$ROOT_DIR"
+
+if ! command -v libtoolize >/dev/null
+then
+	echo "libtoolize: command not found, falling back to glibtoolize" >&2
+	alias libtoolize=glibtoolize
 fi
-set -ex
+
 mkdir -p m4
-aclocal -I m4 -I ${dataroot}/aclocal
-$LIBTOOLIZE --copy --force
+aclocal
+libtoolize --copy --force
 autoheader
 automake --add-missing --copy --foreign
 autoconf
+
+cd "$WORK_DIR"
+"$ROOT_DIR"/configure "$@"
